repos:
- repo: local
  hooks:
  - id: formatter
    name: Ruff Formatter
    entry: ruff format src/ tests/
    language: system
    always_run: true
    pass_filenames: false
  - id: ruff 
    name: Ruff Linter
    entry: ruff check src/ --fix
    language: system
    always_run: true
    pass_filenames: false
  - id: unit tests 
    name: Unit tests
    entry: pytest tests/unit/
    language: system
    always_run: true
    pass_filenames: false