repos:
- repo: local
  hooks:
  - id: ruff 
    name: Ruff
    entry: ruff check src/ --fix
    language: system
    always_run: true
    pass_filenames: false
  - id: unit tests 
    name: Unit tests
    entry: pytest tests/unit/
    language: system
    always_run: true
    pass_filenames: false