# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ENV_FILE: ${{ vars.ENV_FILE_CONTENT }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements.txt
    - name: Setup .env file
      run: |
        echo "!!!!!!!! DEBUG:"
        echo $ENV_FILE_CONTENT
        echo ${{ vars.ENV_FILE_CONTENT }}
        echo ${{ env.ENV_FILE_CONTENT }}
        echo ${{ env.ENV_FILE }}
        echo ${{ env.ENV_FILE }} > secrets/.env
        cat  secrets/.env
    - name: Lint with ruff
      run: |
        ruff check src/
    - name: Unit tests
      run: |
        pytest tests/unit/
